In [69]:
from selenium import webdriver
import pandas as pd

### **Part 1**

• Scrap books title, and prices from https://www.amazon.in/gp/bestsellers/books/ webpage and save it as a
CSV file.

#### **Initialize the web driver object**

In [70]:
driver = webdriver.Chrome()

In [71]:
driver.get("https://www.amazon.in/gp/bestsellers/books/")

#### **Extract the Books' Data**

In [72]:
# Get Books' data
books_title = driver.find_elements("xpath", "//span/div[@class=\"_cDEzb_p13n-sc-css-line-clamp-1_1Fn1y\"]")       
books_author = driver.find_elements("xpath", "//a[@class=\"a-size-small a-link-child\"]") 
books_rating = driver.find_elements("xpath", "//span[@class=\"a-icon-alt\"]")
books_items_bought = driver.find_elements("xpath", "//a[@class=\"a-link-normal\"]/span[@class=\"a-size-small\"]")
books_price = driver.find_elements("xpath", "//span[@class=\"_cDEzb_p13n-sc-price_3mJ9Z\"]")

#### **Map the extracted data to python dictionary**

In [76]:
# Create a dictionary to store Book Data
book_data = {'Title': [],
             'Author': [],
             'Rating': [],
             'Quantity Bought': [],
             'Price': []}

In [77]:
for idx, zipped_book_info in enumerate(zip(books_title, books_author, books_rating, books_items_bought, books_price)):

    book_title, book_author, book_rating, items_bought, book_price = zipped_book_info     # Get the book's data

    # Visualize the extracted Data
    print(f'##################################### Book {idx+1} Before Refinning Data #####################################')
    print(f'{idx+1}. Title:', book_title.text)
    print(f'{idx+1}. Author:', book_author.text)
    print(f'{idx+1}. Rating:', book_rating.text)
    print(f'{idx+1}. Items Bought:', items_bought.text)
    print(f'{idx+1}. Price:', book_price.text)

    # Refine the data to get the exact information required
    book_title = book_title.text
    book_author = book_author.text
    items_bought = items_bought.text
    book_rating = book_rating.get_attribute("innerText").strip()
    book_price = book_price.text


    print(f'##################################### Book {idx+1} After Refinning Data #####################################')
    print(f'{idx+1}. Title:', book_title)
    print(f'{idx+1}. Author:', book_author)
    print(f'{idx+1}. Items Bought:', items_bought)
    print(f'{idx+1}. Rating:', book_rating)
    print(f'{idx+1}. Price:', book_price)


    # Save the Data in the dictionary
    book_data['Title'].append(book_title)
    book_data['Author'].append(book_author)
    book_data['Rating'].append(book_rating)
    book_data['Quantity Bought'].append(items_bought)
    book_data['Price'].append(book_price)

##################################### Book 1 Before Refinning Data #####################################
1. Title: Thank You for Leaving: Learning to be okay with saying goodbye | A new book by one of India’s highest selling authors - Rithvik Singh
1. Author: Rithvik Singh
1. Rating:
1. Items Bought: 39
1. Price: ₹228.00
##################################### Book 1 After Refinning Data #####################################
1. Title: Thank You for Leaving: Learning to be okay with saying goodbye | A new book by one of India’s highest selling authors - Rithvik Singh
1. Author: Rithvik Singh
1. Items Bought: 39
1. Rating: 4.7 out of 5 stars
1. Price: ₹228.00
##################################### Book 2 Before Refinning Data #####################################
2. Title: Khan Sir Pocket GK General Knowledge (Samanya Gyan) By Khan Sir 2nd Revised September 2024 Edition useful for all competitive Exams
2. Author: Khan Sir
2. Rating:
2. Items Bought: 10
2. Price: ₹231.30
##################################### Book 2 After Refinning Data #####################################
2. Title: Khan Sir Pocket GK General Knowledge (Samanya Gyan) By Khan Sir 2nd Revised September 2024 Edition useful for all competitive Exams
2. Author: Khan Sir
2. Items Bought: 10
2. Rating: 4.2 out of 5 stars
2. Price: ₹231.30
##################################### Book 3 Before Refinning Data #####################################
3. Title: Too Good to Be True : A smart, funny will-they-won’t-they romance by mostlysane
3. Author: Prajakta Koli
3. Rating:
3. Items Bought: 603
3. Price: ₹257.00
##################################### Book 3 After Refinning Data #####################################
3. Title: Too Good to Be True : A smart, funny will-they-won’t-they romance by mostlysane
3. Author: Prajakta Koli
3. Items Bought: 603
3. Rating: 4.4 out of 5 stars
3. Price: ₹257.00
##################################### Book 4 Before Refinning Data #####################################
4. Title: My First Library: Boxset of 10 Board Books for Kids
4. Author: Wonder House Books
4. Rating:
4. Items Bought: 81,889
4. Price: ₹399.00
##################################### Book 4 After Refinning Data #####################################
4. Title: My First Library: Boxset of 10 Board Books for Kids
4. Author: Wonder House Books
4. Items Bought: 81,889
4. Rating: 4.5 out of 5 stars
4. Price: ₹399.00
##################################### Book 5 Before Refinning Data #####################################
5. Title: Meditations
5. Author: Marcus Aurelius
5. Rating:
5. Items Bought: 3,387
5. Price: ₹139.00
##################################### Book 5 After Refinning Data #####################################
5. Title: Meditations
5. Author: Marcus Aurelius
5. Items Bought: 3,387
5. Rating: 4.3 out of 5 stars
5. Price: ₹139.00
##################################### Book 6 Before Refinning Data #####################################
6. Title: The Psychology of Money [Paperback] Morgan Housel [Paperback] Morgan Housel
6. Author: Morgan Housel
6. Rating:
6. Items Bought: 70,307
6. Price: ₹262.00
##################################### Book 6 After Refinning Data #####################################
6. Title: The Psychology of Money [Paperback] Morgan Housel [Paperback] Morgan Housel
6. Author: Morgan Housel
6. Items Bought: 70,307
6. Rating: 4.6 out of 5 stars
6. Price: ₹262.00
##################################### Book 7 Before Refinning Data #####################################
7. Title: Atomic Habits
7. Author: James Clear
7. Rating:
7. Items Bought: 101,626
7. Price: ₹549.00
##################################### Book 7 After Refinning Data #####################################
7. Title: Atomic Habits
7. Author: James Clear
7. Items Bought: 101,626
7. Rating: 4.6 out of 5 stars
7. Price: ₹549.00
##################################### Book 8 Before Refinning Data #####################################
8. Title: Amma Diarylo Konni Pageelu
8. Author: Ravi Mantri
8. Rating:
8. Items Bought: 1,537
8. Price: ₹220.00
##################################### Book 8 After Refinning Data #####################################
8. Title: Amma Diarylo Konni Pageelu
8. Author: Ravi Mantri
8. Items Bought: 1,537
8. Rating: 4.7 out of 5 stars
8. Price: ₹220.00
##################################### Book 9 Before Refinning Data #####################################
9. Title: My First Book of Patterns Pencil Control: Patterns Practice book for kids (Pattern Writing)
9. Author: Wonder House Books
9. Rating:
9. Items Bought: 29,474
9. Price: ₹129.00
##################################### Book 9 After Refinning Data #####################################
9. Title: My First Book of Patterns Pencil Control: Patterns Practice book for kids (Pattern Writing)
9. Author: Wonder House Books
9. Items Bought: 29,474
9. Rating: 4.4 out of 5 stars
9. Price: ₹129.00
##################################### Book 10 Before Refinning Data #####################################
10. Title: GUNAHO KA DEVTA
10. Author: Thibaut Meurisse
10. Rating:
10. Items Bought: 1,395
10. Price: ₹218.00
##################################### Book 10 After Refinning Data #####################################
10. Title: GUNAHO KA DEVTA
10. Author: Thibaut Meurisse
10. Items Bought: 1,395
10. Rating: 4.6 out of 5 stars
10. Price: ₹218.00
##################################### Book 11 Before Refinning Data #####################################
11. Title: DHARAMVEER BHARTI
11. Author: Renuka Gavrani
11. Rating:
11. Items Bought: 13,135
11. Price: ₹199.00
##################################### Book 11 After Refinning Data #####################################
11. Title: DHARAMVEER BHARTI
11. Author: Renuka Gavrani
11. Items Bought: 13,135
11. Rating: 4.4 out of 5 stars
11. Price: ₹199.00
##################################### Book 12 Before Refinning Data #####################################
12. Title: Dopamine Detox : A Short Guide to Remove Distractions and Get Your Brain to Do Hard Things
12. Author: Wonder House Books
12. Rating:
12. Items Bought: 2,553
12. Price: ₹200.00
##################################### Book 12 After Refinning Data #####################################
12. Title: Dopamine Detox : A Short Guide to Remove Distractions and Get Your Brain to Do Hard Things
12. Author: Wonder House Books
12. Items Bought: 2,553
12. Rating: 4.4 out of 5 stars
12. Price: ₹200.00
##################################### Book 13 Before Refinning Data #####################################
13. Title: The Art of Being Alone: Loneliness Was My Cage, Solitude Is My Home (English)
13. Author: Nick Trenton
13. Rating:
13. Items Bought: 1,604
13. Price: ₹124.00
##################################### Book 13 After Refinning Data #####################################
13. Title: The Art of Being Alone: Loneliness Was My Cage, Solitude Is My Home (English)
13. Author: Nick Trenton
13. Items Bought: 1,604
13. Rating: 4.6 out of 5 stars
13. Price: ₹124.00
##################################### Book 14 Before Refinning Data #####################################
14. Title: White Nights – Fyodor Dostoyevsky | A Million-Copy Bestseller | A Timeless Story of Love, Longing & Solitude – Penguin Classics
14. Author: Joseph Murphy
14. Rating:
14. Items Bought: 6,247
14. Price: ₹199.00
##################################### Book 14 After Refinning Data #####################################
14. Title: White Nights – Fyodor Dostoyevsky | A Million-Copy Bestseller | A Timeless Story of Love, Longing & Solitude – Penguin Classics
14. Author: Joseph Murphy
14. Items Bought: 6,247
14. Rating: 4.5 out of 5 stars
14. Price: ₹199.00
##################################### Book 15 Before Refinning Data #####################################
15. Title: Fyodor Dostoyevsky
15. Author: Maple Press
15. Rating:
15. Items Bought: 121
15. Price: ₹191.00
##################################### Book 15 After Refinning Data #####################################
15. Title: Fyodor Dostoyevsky
15. Author: Maple Press
15. Items Bought: 121
15. Rating: 4.4 out of 5 stars
15. Price: ₹191.00
##################################### Book 16 Before Refinning Data #####################################
16. Title: Animals Tales From Panchtantra: Timeless Stories for Children From Ancient India
16. Author: Maple Press
16. Rating:
16. Items Bought: 50,092
16. Price: ₹149.00
##################################### Book 16 After Refinning Data #####################################
16. Title: Animals Tales From Panchtantra: Timeless Stories for Children From Ancient India
16. Author: Maple Press
16. Items Bought: 50,092
16. Rating: 4.5 out of 5 stars
16. Price: ₹149.00
##################################### Book 17 Before Refinning Data #####################################
17. Title: The Art of Letting Go
17. Author: Joseph Nguyen
17. Rating:
17. Items Bought: 493
17. Price: ₹150.00
##################################### Book 17 After Refinning Data #####################################
17. Title: The Art of Letting Go
17. Author: Joseph Nguyen
17. Items Bought: 493
17. Rating: 4.3 out of 5 stars
17. Price: ₹150.00
##################################### Book 18 Before Refinning Data #####################################
18. Title: The Power of Your Subconscious Mind: Original Classic Edition | Premium Paperback
18. Author: Dr. Binay Karna
18. Rating:
18. Items Bought: 4,602
18. Price: ₹174.00
##################################### Book 18 After Refinning Data #####################################
18. Title: The Power of Your Subconscious Mind: Original Classic Edition | Premium Paperback
18. Author: Dr. Binay Karna
18. Items Bought: 4,602
18. Rating: 4.3 out of 5 stars
18. Price: ₹174.00
##################################### Book 19 Before Refinning Data #####################################
19. Title: Story Books for Kids - Second Reader (Illustrated) (Set of 6 Books) - Phonic stories - Bedtime Stories - 3 Years to 6 Years Old - Read Aloud to Infants, Toddlers
19. Author: Dr. Manish Raj (MR. Sir)
19. Rating:
19. Items Bought: 89,980
19. Price: ₹187.00
##################################### Book 19 After Refinning Data #####################################
19. Title: Story Books for Kids - Second Reader (Illustrated) (Set of 6 Books) - Phonic stories - Bedtime Stories - 3 Years to 6 Years Old - Read Aloud to Infants, Toddlers
19. Author: Dr. Manish Raj (MR. Sir)
19. Items Bought: 89,980
19. Rating: 4.5 out of 5 stars
19. Price: ₹187.00
##################################### Book 20 Before Refinning Data #####################################
20. Title: Little Colouring Books for Kids (Set of 10 Books) - Gift to children for painting, drawing and coloring - Alphabets, Animals, Birds, Flags, Flowers, ... Transport, Vegetables - 3 to 6 years old
20. Author: Wonder House Books
20. Rating:
20. Items Bought: 9,751
20. Price: ₹200.00
##################################### Book 20 After Refinning Data #####################################
20. Title: Little Colouring Books for Kids (Set of 10 Books) - Gift to children for painting, drawing and coloring - Alphabets, Animals, Birds, Flags, Flowers, ... Transport, Vegetables - 3 to 6 years old
20. Author: Wonder House Books
20. Items Bought: 9,751
20. Rating: 4.5 out of 5 stars
20. Price: ₹200.00
##################################### Book 21 Before Refinning Data #####################################
21. Title: Man's Search For Meaning: The classic tribute to hope from the Holocaust | Must read classics by Victor E. Frankl
21. Author: Nikhil Gupta
21. Rating:
21. Items Bought: 57,477
21. Price: ₹372.00
##################################### Book 21 After Refinning Data #####################################
21. Title: Man's Search For Meaning: The classic tribute to hope from the Holocaust | Must read classics by Victor E. Frankl
21. Author: Nikhil Gupta
21. Items Bought: 57,477
21. Rating: 4.6 out of 5 stars
21. Price: ₹372.00
##################################### Book 22 Before Refinning Data #####################################
22. Title: Victor E. Frankl
22. Author: Robert T. Kiyosaki
22. Rating:
22. Items Bought: 21
22. Price: ₹220.00
##################################### Book 22 After Refinning Data #####################################
22. Title: Victor E. Frankl
22. Author: Robert T. Kiyosaki
22. Items Bought: 21
22. Rating: 4.2 out of 5 stars
22. Price: ₹220.00
##################################### Book 23 Before Refinning Data #####################################
23. Title: Don't Believe Everything You Think (English)
23. Author: Maple Press
23. Rating:
23. Items Bought: 3,712
23. Price: ₹387.00
##################################### Book 23 After Refinning Data #####################################
23. Title: Don't Believe Everything You Think (English)
23. Author: Maple Press
23. Items Bought: 3,712
23. Rating: 4.7 out of 5 stars
23. Price: ₹387.00
##################################### Book 24 Before Refinning Data #####################################
24. Title: Ikigai: Japanese secret to long and happy life
24. Author: M Laxmikanth
24. Rating:
24. Items Bought: 13,102
24. Price: ₹199.00
##################################### Book 24 After Refinning Data #####################################
24. Title: Ikigai: Japanese secret to long and happy life
24. Author: M Laxmikanth
24. Items Bought: 13,102
24. Rating: 4.3 out of 5 stars
24. Price: ₹199.00
##################################### Book 25 Before Refinning Data #####################################
25. Title: Héctor García Francesc Miralles
25. Author: Physics Wallah
25. Rating:
25. Items Bought: 1,039
25. Price: ₹299.00
##################################### Book 25 After Refinning Data #####################################
25. Title: Héctor García Francesc Miralles
25. Author: Physics Wallah
25. Items Bought: 1,039
25. Rating: 4.5 out of 5 stars
25. Price: ₹299.00
##################################### Book 26 Before Refinning Data #####################################
26. Title: Lucent Gk 2024 New Edition - English | Lucent's General Knowledge 2024 in English | Latest Updated Contents - 14th 2024 & Updated Page 494 & MRP 295 | Original Book & 3-D Hologam with Scratch | Useful all Govt and Other 2024-25 Exams
26. Author: Paulo Coelho
26. Rating:
26. Items Bought: 32,994
26. Price: ₹359.00
##################################### Book 26 After Refinning Data #####################################
26. Title: Lucent Gk 2024 New Edition - English | Lucent's General Knowledge 2024 in English | Latest Updated Contents - 14th 2024 & Updated Page 494 & MRP 295 | Original Book & 3-D Hologam with Scratch | Useful all Govt and Other 2024-25 Exams
26. Author: Paulo Coelho
26. Items Bought: 32,994
26. Rating: 4.5 out of 5 stars
26. Price: ₹359.00

#### **Convert the python dictionary to DataFrame**

In [78]:
book_data_df = pd.DataFrame(book_data)

In [79]:
book_data_df.head()

,Title,Author,Rating,Quantity Bought,Price
0,Thank You for Leaving: Learning to be okay wit...,Rithvik Singh,4.7 out of 5 stars,39,₹228.00
1,Khan Sir Pocket GK General Knowledge (Samanya ...,Khan Sir,4.2 out of 5 stars,10,₹231.30
2,"Too Good to Be True : A smart, funny will-they...",Prajakta Koli,4.4 out of 5 stars,603,₹257.00
3,My First Library: Boxset of 10 Board Books for...,Wonder House Books,4.5 out of 5 stars,"81,889",₹399.00
4,Meditations,Marcus Aurelius,4.3 out of 5 stars,"3,387",₹139.00

#### **Save the DataFrame AS CSV File**

In [80]:
book_data_df.to_csv('book_data.csv', index=False)

### **Part 2**

• Your task is to scrape the top 200 movies with their lifetime collection and  release data and save it in a CSV file. The website we will be using is box office mojo  https://www.boxofficemojo.com/chart/top_lifetime_gross/?area=XWW

#### **Initialize the web driver object**

In [83]:
driver = webdriver.Chrome()

In [84]:
driver.get("https://www.boxofficemojo.com/chart/top_lifetime_gross/?area=XWW")

#### **Extract the Movies' Data**

In [85]:
# Get Movies' data
movies_rank = driver.find_elements("xpath", "//tr/td[@class=\"a-text-right mojo-header-column mojo-truncate mojo-field-type-rank\"]") 
movies_title = driver.find_elements("xpath", "//tr/td[@class=\"a-text-left mojo-field-type-title\"]")       
movies_lifetime_gross = driver.find_elements("xpath", "//tr/td[@class=\"a-text-right mojo-field-type-money\"]")
movies_year = driver.find_elements("xpath", "//tr/td[@class=\"a-text-left mojo-field-type-year\"]")

#### **Map the extracted data to python dictionary**

In [91]:
# Create a dictionary to store Movie Data
movie_data = {'Title': [],
              'Rank': [],
              'Lifetime Gross': [],
              'Year': []}

In [92]:
for idx, zipped_movie_info in enumerate(zip(movies_rank, movies_title, movies_lifetime_gross, movies_year)):

    movie_rank, movie_title, movie_lifetime_gross, movie_year = zipped_movie_info     # Get the movie's data

    # Visualize the extracted Data
    print(f'##################################### Movie {idx+1} Data #####################################')
    print(f'{idx+1}. Title:', movie_title.text)
    print(f'{idx+1}. Rank:', movie_rank.text)
    print(f'{idx+1}. Lifetime Gross:', movie_lifetime_gross.text)
    print(f'{idx+1}. Year:', movie_year.text)

    # Refine the data to get the exact information required
    movie_rank = movie_rank.text
    movie_title = movie_title.text
    movie_lifetime_gross = movie_lifetime_gross.text
    movie_year = movie_year.text


    # Save the Data in the dictionary
    movie_data['Title'].append(movie_title)
    movie_data['Rank'].append(movie_rank)
    movie_data['Lifetime Gross'].append(movie_lifetime_gross)
    movie_data['Year'].append(movie_year)

##################################### Movie 1 Data #####################################
1. Title: Avatar
1. Rank: 1
1. Lifetime Gross: $2,923,710,708
1. Year: 2009
##################################### Movie 2 Data #####################################
2. Title: Avengers: Endgame
2. Rank: 2
2. Lifetime Gross: $2,799,439,100
2. Year: 2019
##################################### Movie 3 Data #####################################
3. Title: Avatar: The Way of Water
3. Rank: 3
3. Lifetime Gross: $2,320,250,281
3. Year: 2022
##################################### Movie 4 Data #####################################
4. Title: Titanic
4. Rank: 4
4. Lifetime Gross: $2,264,812,968
4. Year: 1997
##################################### Movie 5 Data #####################################
5. Title: Star Wars: Episode VII - The Force Awakens
5. Rank: 5
5. Lifetime Gross: $2,071,310,218
5. Year: 2015
##################################### Movie 6 Data #####################################
6. Title: Avengers: Infinity War
6. Rank: 6
6. Lifetime Gross: $2,052,415,039
6. Year: 2018
##################################### Movie 7 Data #####################################
7. Title: Spider-Man: No Way Home
7. Rank: 7
7. Lifetime Gross: $1,952,732,181
7. Year: 2021
##################################### Movie 8 Data #####################################
8. Title: Inside Out 2
8. Rank: 8
8. Lifetime Gross: $1,698,863,816
8. Year: 2024
##################################### Movie 9 Data #####################################
9. Title: Jurassic World
9. Rank: 9
9. Lifetime Gross: $1,671,537,444
9. Year: 2015
##################################### Movie 10 Data #####################################
10. Title: The Lion King
10. Rank: 10
10. Lifetime Gross: $1,662,020,819
10. Year: 2019
##################################### Movie 11 Data #####################################
11. Title: The Avengers
11. Rank: 11
11. Lifetime Gross: $1,520,538,536
11. Year: 2012
##################################### Movie 12 Data #####################################
12. Title: Furious 7
12. Rank: 12
12. Lifetime Gross: $1,515,342,457
12. Year: 2015
##################################### Movie 13 Data #####################################
13. Title: Top Gun: Maverick
13. Rank: 13
13. Lifetime Gross: $1,495,696,292
13. Year: 2022
##################################### Movie 14 Data #####################################
14. Title: Frozen II
14. Rank: 14
14. Lifetime Gross: $1,453,683,476
14. Year: 2019
##################################### Movie 15 Data #####################################
15. Title: Barbie
15. Rank: 15
15. Lifetime Gross: $1,447,038,421
15. Year: 2023
##################################### Movie 16 Data #####################################
16. Title: Avengers: Age of Ultron
16. Rank: 16
16. Lifetime Gross: $1,405,018,048
16. Year: 2015
##################################### Movie 17 Data #####################################
17. Title: The Super Mario Bros. Movie
17. Rank: 17
17. Lifetime Gross: $1,360,847,665
17. Year: 2023
##################################### Movie 18 Data #####################################
18. Title: Black Panther
18. Rank: 18
18. Lifetime Gross: $1,349,926,083
18. Year: 2018
##################################### Movie 19 Data #####################################
19. Title: Harry Potter and the Deathly Hallows: Part 2
19. Rank: 19
19. Lifetime Gross: $1,342,499,744
19. Year: 2011
##################################### Movie 20 Data #####################################
20. Title: Deadpool & Wolverine
20. Rank: 20
20. Lifetime Gross: $1,338,073,645
20. Year: 2024
##################################### Movie 21 Data #####################################
21. Title: Star Wars: Episode VIII - The Last Jedi
21. Rank: 21
21. Lifetime Gross: $1,334,407,706
21. Year: 2017
##################################### Movie 22 Data #####################################
22. Title: Jurassic World: Fallen Kingdom
22. Rank: 22
22. Lifetime Gross: $1,310,469,037
22. Year: 2018
##################################### Movie 23 Data #####################################
23. Title: Frozen
23. Rank: 23
23. Lifetime Gross: $1,306,450,154
23. Year: 2013
##################################### Movie 24 Data #####################################
24. Title: Iron Man 3
24. Rank: 24
24. Lifetime Gross: $1,266,152,644
24. Year: 2013
##################################### Movie 25 Data #####################################
25. Title: Beauty and the Beast
25. Rank: 25
25. Lifetime Gross: $1,266,115,964
25. Year: 2017
##################################### Movie 26 Data #####################################
26. Title: Incredibles 2
26. Rank: 26
26. Lifetime Gross: $1,243,225,667
26. Year: 2018
##################################### Movie 27 Data #####################################
27. Title: The Fate of the Furious
27. Rank: 27
27. Lifetime Gross: $1,236,009,236
27. Year: 2017
##################################### Movie 28 Data #####################################
28. Title: Minions
28. Rank: 28
28. Lifetime Gross: $1,159,457,503
28. Year: 2015
##################################### Movie 29 Data #####################################
29. Title: Captain America: Civil War
29. Rank: 29
29. Lifetime Gross: $1,155,046,416
29. Year: 2016
##################################### Movie 30 Data #####################################
30. Title: Aquaman
30. Rank: 30
30. Lifetime Gross: $1,152,028,393
30. Year: 2018
##################################### Movie 31 Data #####################################
31. Title: The Lord of the Rings: The Return of the King
31. Rank: 31
31. Lifetime Gross: $1,138,267,561
31. Year: 2003
##################################### Movie 32 Data #####################################
32. Title: Spider-Man: Far from Home
32. Rank: 32
32. Lifetime Gross: $1,132,705,055
32. Year: 2019
##################################### Movie 33 Data #####################################
33. Title: Captain Marvel
33. Rank: 33
33. Lifetime Gross: $1,131,416,446
33. Year: 2019
##################################### Movie 34 Data #####################################
34. Title: Transformers: Dark of the Moon
34. Rank: 34
34. Lifetime Gross: $1,123,794,079
34. Year: 2011
##################################### Movie 35 Data #####################################
35. Title: The Dark Knight Rises
35. Rank: 35
35. Lifetime Gross: $1,114,976,407
35. Year: 2012
##################################### Movie 36 Data #####################################
36. Title: Skyfall
36. Rank: 36
36. Lifetime Gross: $1,108,594,137
36. Year: 2012
##################################### Movie 37 Data #####################################
37. Title: Transformers: Age of Extinction
37. Rank: 37
37. Lifetime Gross: $1,105,261,713
37. Year: 2014
##################################### Movie 38 Data #####################################
38. Title: Jurassic Park
38. Rank: 38
38. Lifetime Gross: $1,104,379,926
38. Year: 1993
##################################### Movie 39 Data #####################################
39. Title: Joker
39. Rank: 39
39. Lifetime Gross: $1,078,958,629
39. Year: 2019
##################################### Movie 40 Data #####################################
40. Title: Star Wars: Episode IX - The Rise of Skywalker
40. Rank: 40
40. Lifetime Gross: $1,077,022,372
40. Year: 2019
##################################### Movie 41 Data #####################################
41. Title: Toy Story 4
41. Rank: 41
41. Lifetime Gross: $1,073,841,394
41. Year: 2019
##################################### Movie 42 Data #####################################
42. Title: Toy Story 3
42. Rank: 42
42. Lifetime Gross: $1,067,316,101
42. Year: 2010
##################################### Movie 43 Data #####################################
43. Title: Pirates of the Caribbean: Dead Man's Chest
43. Rank: 43
43. Lifetime Gross: $1,066,179,747
43. Year: 2006
##################################### Movie 44 Data #####################################
44. Title: Rogue One: A Star Wars Story
44. Rank: 44
44. Lifetime Gross: $1,058,684,742
44. Year: 2016
##################################### Movie 45 Data #####################################
45. Title: Aladdin
45. Rank: 45
45. Lifetime Gross: $1,054,304,000
45. Year: 2019
##################################### Movie 46 Data #####################################
46. Title: Moana 2
46. Rank: 46
46. Lifetime Gross: $1,050,077,511
46. Year: 2024
##################################### Movie 47 Data #####################################
47. Title: Pirates of the Caribbean: On Stranger Tides
47. Rank: 47
47. Lifetime Gross: $1,046,721,266
47. Year: 2011
##################################### Movie 48 Data #####################################
48. Title: Star Wars: Episode I - The Phantom Menace
48. Rank: 48
48. Lifetime Gross: $1,046,515,409
48. Year: 1999
##################################### Movie 49 Data #####################################
49. Title: Despicable Me 3
49. Rank: 49
49. Lifetime Gross: $1,034,800,131
49. Year: 2017
##################################### Movie 50 Data #####################################
50. Title: Finding Dory
50. Rank: 50
50. Lifetime Gross: $1,029,266,989
50. Year: 2016
##################################### Movie 51 Data #####################################
51. Title: Harry Potter and the Sorcerer's Stone
51. Rank: 51
51. Lifetime Gross: $1,026,414,475
51. Year: 2001
##################################### Movie 52 Data #####################################
52. Title: Zootopia
52. Rank: 52
52. Lifetime Gross: $1,025,521,689
52. Year: 2016
##################################### Movie 53 Data #####################################
53. Title: Alice in Wonderland
53. Rank: 53
53. Lifetime Gross: $1,025,468,216
53. Year: 2010
##################################### Movie 54 Data #####################################
54. Title: The Hobbit: An Unexpected Journey
54. Rank: 54
54. Lifetime Gross: $1,017,107,150
54. Year: 2012
##################################### Movie 55 Data #####################################
55. Title: The Dark Knight
55. Rank: 55
55. Lifetime Gross: $1,009,057,329
55. Year: 2008
##################################### Movie 56 Data #####################################
56. Title: Jurassic World Dominion
56. Rank: 56
56. Lifetime Gross: $1,001,978,080
56. Year: 2022
##################################### Movie 57 Data #####################################
57. Title: The Lion King
57. Rank: 57
57. Lifetime Gross: $979,161,373
57. Year: 1994
##################################### Movie 58 Data #####################################
58. Title: Oppenheimer
58. Rank: 58
58. Lifetime Gross: $975,594,978
58. Year: 2023
##################################### Movie 59 Data #####################################
59. Title: Harry Potter and the Deathly Hallows: Part 1
59. Rank: 59
59. Lifetime Gross: $974,919,063
59. Year: 2010
##################################### Movie 60 Data #####################################
60. Title: Despicable Me 2
60. Rank: 60
60. Lifetime Gross: $970,766,005
60. Year: 2013
##################################### Movie 61 Data #####################################
61. Title: Despicable Me 4
61. Rank: 61
61. Lifetime Gross: $969,126,452
61. Year: 2024
##################################### Movie 62 Data #####################################
62. Title: The Jungle Book
62. Rank: 62
62. Lifetime Gross: $967,724,775
62. Year: 2016
##################################### Movie 63 Data #####################################
63. Title: Jumanji: Welcome to the Jungle
63. Rank: 63
63. Lifetime Gross: $962,544,585
63. Year: 2017
##################################### Movie 64 Data #####################################
64. Title: The Hobbit: The Battle of the Five Armies
64. Rank: 64
64. Lifetime Gross: $962,253,946
64. Year: 2014
##################################### Movie 65 Data #####################################
65. Title: Pirates of the Caribbean: At World's End
65. Rank: 65
65. Lifetime Gross: $961,691,209
65. Year: 2007
##################################### Movie 66 Data #####################################
66. Title: The Hobbit: The Desolation of Smaug
66. Rank: 66
66. Lifetime Gross: $959,079,095
66. Year: 2013
##################################### Movie 67 Data #####################################
67. Title: Doctor Strange in the Multiverse of Madness
67. Rank: 67
67. Lifetime Gross: $955,775,804
67. Year: 2022
##################################### Movie 68 Data #####################################
68. Title: Harry Potter and the Order of the Phoenix
68. Rank: 68
68. Lifetime Gross: $942,862,581
68. Year: 2007
##################################### Movie 69 Data #####################################
69. Title: Finding Nemo
69. Rank: 69
69. Lifetime Gross: $941,637,960
69. Year: 2003
##################################### Movie 70 Data #####################################
70. Title: Harry Potter and the Half-Blood Prince
70. Rank: 70
70. Lifetime Gross: $941,055,851
70. Year: 2009
##################################### Movie 71 Data #####################################
71. Title: Minions: The Rise of Gru
71. Rank: 71
71. Lifetime Gross: $940,482,695
71. Year: 2022
##################################### Movie 72 Data #####################################
72. Title: The Lord of the Rings: The Two Towers
72. Rank: 72
72. Lifetime Gross: $938,242,927
72. Year: 2002
##################################### Movie 73 Data #####################################
73. Title: Shrek 2
73. Rank: 73
73. Lifetime Gross: $932,530,034
73. Year: 2004
##################################### Movie 74 Data #####################################
74. Title: Bohemian Rhapsody
74. Rank: 74
74. Lifetime Gross: $910,813,521
74. Year: 2018
##################################### Movie 75 Data #####################################
75. Title: The Battle at Lake Changjin
75. Rank: 75
75. Lifetime Gross: $902,548,476
75. Year: 2021
##################################### Movie 76 Data #####################################
76. Title: Harry Potter and the Goblet of Fire
76. Rank: 76
76. Lifetime Gross: $897,468,952
76. Year: 2005
##################################### Movie 77 Data #####################################
77. Title: Spider-Man 3
77. Rank: 77
77. Lifetime Gross: $891,679,447
77. Year: 2007
##################################### Movie 78 Data #####################################
78. Title: The Lord of the Rings: The Fellowship of the Ring
78. Rank: 78
78. Lifetime Gross: $888,171,906
78. Year: 2001
##################################### Movie 79 Data #####################################
79. Title: Ice Age: Dawn of the Dinosaurs
79. Rank: 79
79. Lifetime Gross: $886,686,817
79. Year: 2009
##################################### Movie 80 Data #####################################
80. Title: Harry Potter and the Chamber of Secrets
80. Rank: 80
80. Lifetime Gross: $882,740,355
80. Year: 2002
##################################### Movie 81 Data #####################################
81. Title: Spider-Man: Homecoming
81. Rank: 81
81. Lifetime Gross: $880,960,014
81. Year: 2017
##################################### Movie 82 Data #####################################
82. Title: Spectre
82. Rank: 82
82. Lifetime Gross: $880,707,597
82. Year: 2015
##################################### Movie 83 Data #####################################
83. Title: Ice Age: Continental Drift
83. Rank: 83
83. Lifetime Gross: $877,244,782
83. Year: 2012
##################################### Movie 84 Data #####################################
84. Title: The Secret Life of Pets
84. Rank: 84
84. Lifetime Gross: $875,698,161
84. Year: 2016
##################################### Movie 85 Data #####################################
85. Title: Batman v Superman: Dawn of Justice
85. Rank: 85
85. Lifetime Gross: $874,362,803
85. Year: 2016
##################################### Movie 86 Data #####################################
86. Title: Wolf Warrior 2
86. Rank: 86
86. Lifetime Gross: $870,325,439
86. Year: 2017
##################################### Movie 87 Data #####################################
87. Title: The Hunger Games: Catching Fire
87. Rank: 87
87. Lifetime Gross: $865,011,746
87. Year: 2013
##################################### Movie 88 Data #####################################
88. Title: Guardians of the Galaxy Vol. 2
88. Rank: 88
88. Lifetime Gross: $863,756,903
88. Year: 2017
##################################### Movie 89 Data #####################################
89. Title: Black Panther: Wakanda Forever
89. Rank: 89
89. Lifetime Gross: $859,208,836
89. Year: 2022
##################################### Movie 90 Data #####################################
90. Title: Inside Out
90. Rank: 90
90. Lifetime Gross: $859,076,254
90. Year: 2015
##################################### Movie 91 Data #####################################
91. Title: Venom
91. Rank: 91
91. Lifetime Gross: $856,085,161
91. Year: 2018
##################################### Movie 92 Data #####################################
92. Title: Thor: Ragnarok
92. Rank: 92
92. Lifetime Gross: $855,301,806
92. Year: 2017
##################################### Movie 93 Data #####################################
93. Title: Star Wars: Episode III - Revenge of the Sith
93. Rank: 93
93. Lifetime Gross: $850,035,635
93. Year: 2005
##################################### Movie 94 Data #####################################
94. Title: The Twilight Saga: Breaking Dawn - Part 2
94. Rank: 94
94. Lifetime Gross: $848,593,948
94. Year: 2012
##################################### Movie 95 Data #####################################
95. Title: Guardians of the Galaxy Vol. 3
95. Rank: 95
95. Lifetime Gross: $845,555,777
95. Year: 2023
##################################### Movie 96 Data #####################################
96. Title: Inception
96. Rank: 96
96. Lifetime Gross: $839,030,630
96. Year: 2010
##################################### Movie 97 Data #####################################
97. Title: Transformers: Revenge of the Fallen
97. Rank: 97
97. Lifetime Gross: $836,303,693
97. Year: 2009
##################################### Movie 98 Data #####################################
98. Title: Spider-Man
98. Rank: 98
98. Lifetime Gross: $825,802,095
98. Year: 2002
##################################### Movie 99 Data #####################################
99. Title: Wonder Woman
99. Rank: 99
99. Lifetime Gross: $823,970,682
99. Year: 2017
##################################### Movie 100 Data #####################################
100. Title: Hi, Mom
100. Rank: 100
100. Lifetime Gross: $822,009,764
100. Year: 2021
##################################### Movie 101 Data #####################################
101. Title: Independence Day
101. Rank: 101
101. Lifetime Gross: $817,400,891
101. Year: 1996
##################################### Movie 102 Data #####################################
102. Title: Fantastic Beasts and Where to Find Them
102. Rank: 102
102. Lifetime Gross: $816,037,575
102. Year: 2016
##################################### Movie 103 Data #####################################
103. Title: Coco
103. Rank: 103
103. Lifetime Gross: $814,641,172
103. Year: 2017
##################################### Movie 104 Data #####################################
104. Title: Harry Potter and the Prisoner of Azkaban
104. Rank: 104
104. Lifetime Gross: $808,485,409
104. Year: 2004
##################################### Movie 105 Data #####################################
105. Title: Shrek the Third
105. Rank: 105
105. Lifetime Gross: $808,308,862
105. Year: 2007
##################################### Movie 106 Data #####################################
106. Title: Jumanji: The Next Level
106. Rank: 106
106. Lifetime Gross: $801,693,929
106. Year: 2019
##################################### Movie 107 Data #####################################
107. Title: E.T. the Extra-Terrestrial
107. Rank: 107
107. Lifetime Gross: $797,307,407
107. Year: 1982

#### **Convert the python dictionary to DataFrame**

In [93]:
movie_data_df = pd.DataFrame(movie_data)

In [94]:
movie_data_df.head()

                                        Title Rank  Lifetime Gross  Year
0                                      Avatar    1  $2,923,710,708  2009
1                           Avengers: Endgame    2  $2,799,439,100  2019
2                    Avatar: The Way of Water    3  $2,320,250,281  2022
3                                     Titanic    4  $2,264,812,968  1997
4  Star Wars: Episode VII - The Force Awakens    5  $2,071,310,218  2015

#### **Save the DataFrame AS CSV File**

In [95]:
movie_data_df.to_csv('movie_data.csv', index=False)